debug: true

server:
  port: 3013
  servlet:
    context-path: /achan-database

mybatis:
  mapper-locations: classpath*:mapper/**/*.xml
  config-location: classpath:mybatis-config.xml
  type-aliases-package: com.achanzhang.mydatabase.achandatabase.beans

spring:
  datasource:
    hikari:
      username: postgres
      password: postgres
      driver-class-name: org.postgresql.Driver
      jdbc-url: jdbc:postgresql://127.0.0.1:5433/test3?autoReconnect=true&ampallowMultiQueries=true
      auto-commit: true
      connection-timeout: 20000
      max-lifetime: 1800000
      minimum-idle: 1
      maximum-pool-size: 5
      idle-timeout: 30000
  flyway:
    enabled: true
    clean-disabled: true
    baseline-on-migrate: true
    baseline-version: 1.3