/*
 Navicat Premium Data Transfer

 Source Server         : localhost_5433
 Source Server Type    : PostgreSQL
 Source Server Version : 100009
 Source Host           : localhost:5433
 Source Catalog        : test1
 Source Schema         : public

 Target Server Type    : PostgreSQL
 Target Server Version : 100009
 File Encoding         : 65001

 Date: 11/06/2020 16:18:14
*/


-- ----------------------------
-- Sequence structure for class_class_number_seq
-- ----------------------------
CREATE SEQUENCE "class_class_number_seq"
INCREMENT 1
MINVALUE  1
MAXVALUE 2147483647
START 1
CACHE 1;

-- ----------------------------
-- Sequence structure for student_student_number_seq
-- ----------------------------
CREATE SEQUENCE "student_student_number_seq"
INCREMENT 1
MINVALUE  1
MAXVALUE 2147483647
START 1
CACHE 1;

-- ----------------------------
-- Table structure for class
-- ----------------------------
CREATE TABLE "class" (
  "class_number" int4 NOT NULL GENERATED BY DEFAULT AS IDENTITY (
INCREMENT 1
MINVALUE  1
MAXVALUE 2147483647
START 1
),
  "class_name" varchar(255) COLLATE "pg_catalog"."default"
)
;
COMMENT ON COLUMN "class"."class_number" IS '班级编号';
COMMENT ON COLUMN "class"."class_name" IS '班级名';

-- ----------------------------
-- Records of class
-- ----------------------------
BEGIN;
INSERT INTO "class" VALUES (1, '1班');
INSERT INTO "class" VALUES (2, '2班');
INSERT INTO "class" VALUES (3, '3班');
COMMIT;

-- ----------------------------
-- Table structure for student
-- ----------------------------
CREATE TABLE "student" (
  "student_number" int4 NOT NULL GENERATED BY DEFAULT AS IDENTITY (
INCREMENT 1
MINVALUE  1
MAXVALUE 2147483647
START 1
),
  "student_name" varchar(64) COLLATE "pg_catalog"."default",
  "class_number" int4
)
;
COMMENT ON COLUMN "student"."student_number" IS '学号';
COMMENT ON COLUMN "student"."student_name" IS '学生姓名';
COMMENT ON COLUMN "student"."class_number" IS '班级号';

-- ----------------------------
-- Records of student
-- ----------------------------
BEGIN;
INSERT INTO "student" VALUES (1, '张三', 1);
INSERT INTO "student" VALUES (2, '李四', 2);
INSERT INTO "student" VALUES (3, '王五', 3);
COMMIT;

-- ----------------------------
-- Alter sequences owned by
-- ----------------------------
ALTER SEQUENCE "class_class_number_seq"
OWNED BY "class"."class_number";
SELECT setval('"class_class_number_seq"', 4, true);
ALTER SEQUENCE "student_student_number_seq"
OWNED BY "student"."student_number";
SELECT setval('"student_student_number_seq"', 4, true);

-- ----------------------------
-- Primary Key structure for table class
-- ----------------------------
ALTER TABLE "class" ADD CONSTRAINT "class_pkey" PRIMARY KEY ("class_number");

-- ----------------------------
-- Primary Key structure for table student
-- ----------------------------
ALTER TABLE "student" ADD CONSTRAINT "student_pkey" PRIMARY KEY ("student_number");

-- ----------------------------
-- Foreign Keys structure for table student
-- ----------------------------
ALTER TABLE "student" ADD CONSTRAINT "fk_class_number" FOREIGN KEY ("class_number") REFERENCES "class" ("class_number") ON DELETE NO ACTION ON UPDATE NO ACTION;
COMMENT ON CONSTRAINT "fk_class_number" ON "student" IS '班级号外键';