CREATE TABLE "class2" (
  "class_number" int4 NOT NULL GENERATED BY DEFAULT AS IDENTITY (
INCREMENT 1
MINVALUE  1
MAXVALUE 2147483647
START 1
),
  "class_name" varchar(255) COLLATE "pg_catalog"."default"
)
;
COMMENT ON COLUMN "class2"."class_number" IS '班级编号';
COMMENT ON COLUMN "class2"."class_name" IS '班级名';